### ISSUE TITLE
bug with --html option

### ISSUE THREAD

**Issue by helio-frota** [bucharest-gold/licenser#44]
using node version 6x

```
fs.js:641
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'lib/resources/template.html'
    at Error (native)
    at Object.fs.openSync (fs.js:641:18)
    at Object.fs.readFileSync (fs.js:509:33)
    at Object.<anonymous> (/home/hf/d/licenser/lib/html.js:5:21)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
```

**Comment by helio-frota** [comment]
https://github.com/bucharest-gold/licenser/pull/46
