### ISSUE TITLE
bug when using option --all with genet project

### ISSUE THREAD

**Issue by helio-frota** [bucharest-gold/licenser#59]
```
✔ ~/d/genet [master|…2] 
16:14 $ licenser --all --file=all.xml
/home/hf/d/licenser/bin/cli.js:12
    name: npmVersion.name,
                    ^

TypeError: Cannot read property 'name' of null
    at entry (/home/hf/d/licenser/bin/cli.js:12:21)
    at add (/home/hf/d/licenser/bin/cli.js:24:27)
    at /home/hf/d/licenser/bin/cli.js:45:11
    at /home/hf/d/licenser/node_modules/license-checker/lib/index.js:373:9
    at /home/hf/d/licenser/node_modules/read-installed/read-installed.js:142:5
    at /home/hf/d/licenser/node_modules/read-installed/read-installed.js:263:14
    at cb (/home/hf/d/licenser/node_modules/slide/lib/async-map.js:47:24)
    at /home/hf/d/licenser/node_modules/read-installed/read-installed.js:263:14
    at cb (/home/hf/d/licenser/node_modules/slide/lib/async-map.js:47:24)
    at /home/hf/d/licenser/node_modules/read-installed/read-installed.js:263:14
```

**Comment by helio-frota** [comment]
info: this was because this kind of name-version with extra `@` and `/` chars
`name: @risingstack/node-pre-gyp , version: 0.6.35 , licenses: BSD-3-Clause`
