### ISSUE TITLE
sometimes license.license is a object instead string

### ISSUE THREAD

**Issue by helio-frota** [bucharest-gold/licenser#61]
this causes error with some functions like this:

```
string
object
/home/hf/d/licenser/lib/listchecker.js:10
      return predicate(keys, license.license.trim());
                                             ^

TypeError: license.license.trim is not a function
    at project.licenses.license.filter (/home/hf/d/licenser/lib/listchecker.js:10:46)
    at Array.filter (native)
    at Object.check (/home/hf/d/licenser/lib/listchecker.js:5:37)
    at /home/hf/d/licenser/bin/cli.js:66:66
    at /home/hf/d/licenser/node_modules/license-checker/lib/index.js:373:9
    at /home/hf/d/licenser/node_modules/read-installed/read-installed.js:142:5
    at /home/hf/d/licenser/node_modules/read-installed/read-installed.js:263:14
    at cb (/home/hf/d/licenser/node_modules/slide/lib/async-map.js:47:24)
    at /home/hf/d/licenser/node_modules/read-installed/read-installed.js:263:14
    at cb (/home/hf/d/licenser/node_modules/slide/lib/async-map.js:47:24)

```

**Comment by helio-frota** [comment]
looks like a 'dual-license' case as array instead string:

```
[ 'AFLv2.1', 'BSD' ]
/home/hf/d/licenser/lib/listchecker.js:9
      return predicate(keys, license.license.trim());
                                             ^

TypeError: license.license.trim is not a function
    at project.licenses.license.filter (/home/hf/d/licenser/lib/listchecker.js:9:46)
    at Array.filter (native)
```
